changes to add help improve and child benefit banner
hmrc/sca-wrapper pull request #13
Opened 2023-03-01 22:36 UTC by kritikarai6

2023-03-02 10:46 UTC, yangwong9664 requested changes

2023-03-02 10:46 UTC, yangwong9664 commented on src/main/resources/reference.conf
> +      help-improve-banner.url = "https://signup.take-part-in-research.service.gov.uk/home?utm_campaign=PTAhomepage&utm_source=Other&utm_medium=other&t=HMRC&id=209"
utm_campaign should probably be a parameter that a service can set in their application.conf file

2023-03-02 10:46 UTC, yangwong9664 commented on src/main/scala/uk/gov/hmrc/sca/config/AppConfig.scala
> +    "https://docs.google.com/forms/d/e/1FAIpQLSegbiz4ClGW0XkC1pY3B02ltiY1V79V7ha0jZinECIz_FvSyg/viewform"
can this url be moved to .conf?

2023-03-02 18:19 UTC, kanchan555-ui submitted a review, later dismissed
approved

2023-03-07 14:15 UTC, yangwong9664 requested changes

2023-03-07 14:15 UTC, yangwong9664 commented on src/main/scala/uk/gov/hmrc/sca/services/WrapperService.scala
>               showUserResearchBanner: Boolean = false,
can showUserResearchBanner be removed, and showHelpImproveBanner moved in its place instead? I think the user research banner was going to be the helpimprove banner but now it's not needed

2023-03-08 14:12 UTC, yangwong9664 approved these changes

2023-03-08 14:25 UTC, merged